package com.brokentelephone.game.features.choose_username.model

object SuggestedUsernames {
    private val all: List<String> = listOf(
        "Scribble King",
        "Bad Artist",
        "Blind Guesser",
        "Doodle Gremlin",
        "Captain Obvious",
        "Miss Squiggle",
        "Chaos Brush",
        "Wrong Answer",
        "Sketch Goblin",
        "No Idea",
        "Pixel Wizard",
        "Fuzzy Logic",
        "Master Guesser",
        "Crayon Bandit",
        "Wobbly Lines",
        "Abstract Mess",
        "Noodle Artist",
        "Total Nonsense",
        "Vague Vision",
        "Potato Painter",
        "Lazy Picasso",
        "Random Blob",
        "Off By One",
        "Lost In Translation",
        "Smudge Lord",
        "Ink Goblin",
        "Stick Figure Pro",
        "Circle Expert",
        "The Guesser",
        "Masterpiece Maybe",
        "Cursed Canvas",
        "Wobbly Wrist",
        "Scribble Witch",
        "Pencil Goblin",
        "Color Blind",
        "Shaky Hand",
        "Mystery Blob",
        "Half A Brain",
        "Doodle Bandit",
        "Parallel Lines",
        "Paint Disaster",
        "Zigzag Hero",
        "Unnamed Legend",
        "Zero Context",
        "Big Brain Energy",
        "Mostly Circles",
        "Not A Artist",
        "Triangle Lord",
        "Squiggle Queen",
        "What Is That",
        "Just Guessing",
        "Famous Nobody",
        "Decent At Best",
        "Certified Chaos",
        "Rubber Duck",
        "404 Art Not Found",
        "Invisible Ink",
        "Color Outside",
        "Pretty Close",
        "Nailed It Maybe",
        "Wild Stroke",
        "Midnight Doodler",
        "Phantom Brush",
        "Artless Wonder",
        "Sketch Specter",
        "Misguided Muse",
        "Blur Master",
        "Scribble Ghost",
        "Foggy Notion",
        "Pen Destroyer",
        "Ink Phantom",
        "Confused Curator",
        "Accidental Art",
        "Doodle Menace",
        "Thumbs Up",
        "Barely Visible",
        "Sketch Demon",
        "Line Breaker",
        "Blot Machine",
        "Guess Again",
        "Cryptic Brush",
        "Spiral Thinker",
        "Mild Disaster",
        "Glitch Artist",
        "Abstract Brain",
        "Rogue Pencil",
        "One Wrong Turn",
        "Splatter King",
        "Eraser Abuser",
        "Almost Art",
        "Broken Pencil",
        "Ink Tornado",
        "Wild Guesser",
        "Squiggle Brain",
        "Hopeless Doodler",
        "Lost Stylus",
        "Pencil Phantom",
        "Chaos Theory",
        "Doodle Reaper",
    )

    fun random10(): List<String> = all.shuffled().take(10)
    fun random(): String = all.random()
}
